
name: Publish on Github, CurseForge & Modrinth

on: [ pull_request, workflow_dispatch ]

env:
  MINECRAFT_VERSION: 1.18.2
  MINECRAFT_VERSION_SHORT: 1.18
  JAVA_VERSION: 17
  VERSION: 1.1.0b+1.18.2
  RELEASE_NAME: Cats Expanded 1.1.0b for Minecraft 1.18.2
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish (CurseForge/Modrinth)
        uses: Kir-Antipov/mc-publish@v2.1
        with:
          modrinth-id: FIzl2Jhk
          # modrinth-featured: true
          # modrinth-unfeature-mode: subset
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          curseforge-id: 576251
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          files-primary: build/libs/!(*-@(dev|sources)).jar

          name: "${{env.RELEASE_NAME}}"
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION_SHORT}}"
          java: "${{env.JAVA_VERSION}}"

          retry-attempts: 2
          retry-delay: 10000

      - name: Publish (Github)
        uses: Kir-Antipov/mc-publish@v3.0
        with:
          github-tag: "v${{env.VERSION}}"
          github-draft: false
          github-token: "${{env.GITHUB_TOKEN}}"

          files-primary: build/libs/!(*-@(dev|sources)).jar
          files-secondary: build/libs/*-@(dev|sources).jar

          name: "${{env.RELEASE_NAME}}"
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"

          retry-attempts: 2
          retry-delay: 10000
